name: Update Leaderboard

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout leaderboard repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.LEADERBOARD }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Build leaderboard
        env:
          READ: ${{ secrets.READ }} # read-only token for student repos
        run: |
          python -u build_leaderboard.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "234437466+LDarg@users.noreply.github.com"
          git config --global user.name "LDarg"
          if git diff --quiet; then
            echo "No leaderboard changes"
          else
            git add leaderboard.json
            git commit -m "Update leaderboard"
            git push
          fi
